import type { SiteDocument } from "../../../../packages/site-contracts/src/site-document.js";
import { LOOKBOOK_IMAGE, HERO_IMAGE, SPLIT_COTTON_IMAGE, SPLIT_LEATHER_IMAGE } from "../data/catalog";

/**
 * A second, unrelated brand proving the same React scene consumes the
 * canonical CMS SiteDocument structure. These values are fixture-only.
 */
export const fieldworkSite: SiteDocument = {
  schemaVersion: 1,
  id: "fieldwork-demonstration",
  theme: "fieldwork",
  design: { accent: "#4C6655", accentSoft: "#C0D3B2", canvas: "#F0EFE7",
    paper: "#FFFFFF", ink: "#19211C" },
  brand: {
    name: "FIELDWORK / STUDIO",
    home: "/",
    description: "The long way around is usually the good one.",
  },
  header: {
    settings: { sticky: true, pill: true },
    announcement: { enabled: false, messages: [] },
    blocks: [{ id: "brand", type: "brand", label: "FIELDWORK / STUDIO", href: "/" }],
  },
  footer: {
    settings: { background: "inverse", copyright: "Illustrative brand fixture" },
    blocks: [],
  },
  pages: [{
    id: "home",
    path: "/",
    title: "The road ahead",
    description: "Illustrative content from another customer identity",
    sections: [{
      id: "fieldwork-curtain-hero",
      type: "media-hero",
      preset: "commons/curtain-hero",
      settings: {
        surface: "image",
        minHeight: "screen",
        spacing: "lg",
        backgroundMediaKey: "fieldwork.hero",
      },
      data: {
        eyebrow: "FIELDWORK / THE OPEN ROAD",
        heading: "THE LONG WAY IS THE GOOD WAY.",
        body: "Out there is where the best stories begin. Make time for every turn, stop, and detour.",
        mediaKey: "fieldwork.hero",
        ctaLabel: "Explore the stories",
        ctaHref: "/stories/",
      },
    }, {
      id: "fieldwork-wardrobe",
      type: "showcase",
      preset: "commons/wardrobe-gallery",
      settings: { surface: "paper", spacing: "lg", minHeight: "auto" },
      data: { eyebrow: "A FEW WAYS TO GET LOST", heading: "Choose your own direction." },
      blocks: [
        { id: "fieldwork-journeys", type: "item",
          data: { title: "Journeys", caption: "Open roads", mediaKey: "fieldwork.journeys",
            href: "/stories/", alt: "Sunset on the open road" } },
        { id: "fieldwork-materials", type: "item",
          data: { title: "Materials", caption: "Wear and weather", mediaKey: "fieldwork.materials",
            href: "/materials/", alt: "Materials and textures" } },
        { id: "fieldwork-archive", type: "item",
          data: { title: "Archives", caption: "Objects that last", mediaKey: "fieldwork.archive",
            href: "/archive/", alt: "Editorial archive" } },
      ],
    }, {
      id: "fieldwork-diptych",
      type: "showcase",
      preset: "commons/split-media",
      settings: { surface: "inverse", spacing: "none", minHeight: "auto" },
      data: { heading: "Between departure and discovery" },
      blocks: [
        { id: "fieldwork-morning", type: "item",
          data: { eyebrow: "STUDY 01 · MORNING", title: "Go beyond the familiar.",
            body: "Leave the map open. Every little turn is part of the story.",
            mediaKey: "fieldwork.morning", href: "/stories/morning/",
            ctaLabel: "Explore morning", alt: "Morning road trip scene" } },
        { id: "fieldwork-evening", type: "item",
          data: { eyebrow: "STUDY 02 · EVENING", title: "Stay for the light.",
            body: "The best discoveries rarely have a strict arrival time.",
            mediaKey: "fieldwork.evening", href: "/stories/evening/",
            ctaLabel: "Explore evening", alt: "Evening landscape" } },
      ],
    }, {
      id: "fieldwork-statement",
      type: "statement",
      preset: "commons/editorial-statement",
      settings: { surface: "paper", spacing: "md", minHeight: "auto" },
      data: { body: "Take the route that leaves you with a better story.",
        ctaLabel: "Browse the journal", ctaHref: "/journal/" },
    }, {
      id: "fieldwork-collection",
      type: "showcase",
      preset: "commons/collection-carousel",
      settings: { surface: "paper", spacing: "lg", minHeight: "auto" },
      data: { eyebrow: "OBJECTS FOR THE JOURNEY", heading: "The collected edit",
        body: "Stories and objects to take with you." },
      blocks: [
        { id: "fieldwork-pack", type: "item",
          data: { title: "Weekend essentials", label: "For the road", group: "Travel",
            badge: "Featured", mediaKey: "fieldwork.journeys", alt: "Travel editorial",
            href: "/collections/travel/" } },
        { id: "fieldwork-journal", type: "item",
          data: { title: "The maker's journal", label: "Behind the work", group: "Stories",
            mediaKey: "fieldwork.materials", alt: "Fabric and material editorial",
            href: "/journal/" } },
        { id: "fieldwork-archive-card", type: "item",
          data: { title: "Field archive", label: "Collected objects", group: "Travel",
            mediaKey: "fieldwork.archive", alt: "Archived materials",
            href: "/collections/archive/" } },
      ],
    }, {
      id: "fieldwork-lookbook",
      type: "showcase",
      preset: "commons/lookbook-hotspots",
      settings: { surface: "inverse", spacing: "lg", minHeight: "auto" },
      data: { eyebrow: "THE EDITORIAL", heading: "Find the interesting details",
        body: "An interactive look at considered design.",
        mediaKey: "fieldwork.hero", alt: "Fieldwork editorial campaign" },
      blocks: [
        { id: "fieldwork-lookbook-story", type: "item",
          data: { title: "The open road", body: "A moment worth remembering.",
            badge: "Chapter 01", hotspotX: 32, hotspotY: 38,
            ctaLabel: "Read the story", href: "/stories/open-road/" } },
        { id: "fieldwork-lookbook-material", type: "item",
          data: { title: "Considered materials", body: "Made for everyday exploration.",
            badge: "Chapter 02", hotspotX: 70, hotspotY: 63,
            ctaLabel: "Explore materials", href: "/materials/" } },
      ],
    }, {
      id: "fieldwork-questions",
      type: "showcase",
      preset: "commons/faq-trust",
      settings: { surface: "paper", spacing: "md", minHeight: "auto" },
      data: { eyebrow: "BEFORE YOU GO", heading: "Questions along the way",
        body: "Answers from the example brand, not verified service guarantees.",
        ctaLabel: "Contact the studio", ctaHref: "/contact/" },
      blocks: [
        { id: "fieldwork-question-one", type: "text",
          data: { title: "Where can I see the collection?", body: "Browse the collection pages and preview editorial work." } },
        { id: "fieldwork-question-two", type: "text",
          data: { title: "Can I customize the layout?", body: "This example uses a reusable section contract with editable blocks." } },
      ],
    }],
  }],
};

export const fieldworkMedia: ReadonlyMap<string, string> = new Map([
  ["fieldwork.hero", LOOKBOOK_IMAGE],
  ["fieldwork.journeys", HERO_IMAGE],
  ["fieldwork.materials", SPLIT_COTTON_IMAGE],
  ["fieldwork.archive", SPLIT_LEATHER_IMAGE],
  ["fieldwork.morning", LOOKBOOK_IMAGE],
  ["fieldwork.evening", HERO_IMAGE],
]);
