import type {
  PagePreset,
  SectionPreset,
} from "@inneranimalmedia/site-contracts";

const common = {
  responsive: { mobileFirst: true as const, containerQuery: true },
  touch: { minimumTarget: 44 },
  safeArea: { enabled: true },
  motion: { reducedMotionSafe: true },
};

export const reviseShowcasePresets: SectionPreset[] = [
  {
    id: "revise/sticky-curtain",
    type: "media-hero",
    variant: "revise/sticky-curtain",
    layout: { width: "full", bleed: "media", gutters: { mode: "none" }, spacing: { block: "none" } },
    ...common,
    data: {},
  },
  {
    id: "revise/wardrobe-rail",
    type: "media-gallery",
    variant: "revise/wardrobe-rail",
    layout: { width: "full", bleed: "background", gutters: { mode: "fluid" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
  {
    id: "revise/dark-promo-grid",
    type: "editorial-grid",
    variant: "revise/dark-promo-grid",
    layout: { width: "full", bleed: "background", gutters: { mode: "fluid" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
  {
    id: "revise/editorial-statement",
    type: "statement",
    variant: "revise/editorial-statement",
    layout: { width: "reading", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "sm" } },
    ...common,
    data: {},
  },
  {
    id: "revise/story-rings",
    type: "stories",
    variant: "revise/story-rings",
    layout: { width: "content", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "sm" } },
    ...common,
    data: {},
  },
  {
    id: "revise/tabbed-products",
    type: "collection-track",
    variant: "revise/tabbed-products",
    layout: { width: "full", bleed: "background", gutters: { mode: "fluid" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
  {
    id: "revise/scroll-text-reveal",
    type: "fullscreen-media-product",
    variant: "revise/scroll-text-reveal",
    layout: { width: "full", bleed: "media", gutters: { mode: "none" }, spacing: { block: "none" } },
    ...common,
    data: {},
  },
  {
    id: "revise/parallax-diptych",
    type: "split-media",
    variant: "revise/parallax-diptych",
    layout: { width: "full", bleed: "media", gutters: { mode: "none" }, spacing: { block: "none" } },
    ...common,
    data: {},
  },
  {
    id: "revise/hotspot-lookbook",
    type: "shop-the-look",
    variant: "revise/hotspot-lookbook",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/pinned-pdp",
    type: "featured-product",
    variant: "revise/pinned-pdp",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/commerce-marquee",
    type: "marquee",
    variant: "revise/commerce-marquee",
    layout: { width: "full", bleed: "background", gutters: { mode: "none" }, spacing: { block: "none" } },
    ...common,
    data: {},
  },
  {
    id: "revise/logo-track",
    type: "logo-track",
    variant: "revise/logo-track",
    layout: { width: "full", bleed: "none", gutters: { mode: "none" }, spacing: { block: "sm" } },
    ...common,
    data: {},
  },
  {
    id: "revise/testimonials",
    type: "testimonials",
    variant: "revise/testimonials",
    layout: { width: "content", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
  {
    id: "revise/newsletter",
    type: "cta-band",
    variant: "revise/newsletter",
    layout: { width: "full", bleed: "background", gutters: { mode: "fluid" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
  {
    id: "revise/faq",
    type: "faq",
    variant: "revise/faq",
    layout: { width: "content", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
  {
    id: "revise/trust-row",
    type: "trust-row",
    variant: "revise/trust-row",
    layout: { width: "full", bleed: "background", gutters: { mode: "fluid" }, spacing: { block: "sm" } },
    ...common,
    data: {},
  },
  {
    id: "revise/merch-lab",
    type: "commerce-offers",
    variant: "revise/merch-lab",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/sticky-summary",
    type: "bundle-builder",
    variant: "revise/sticky-summary",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/pinned-media-grid",
    type: "collection-split-media",
    variant: "revise/pinned-media-grid",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/brand-film",
    type: "brand-film",
    variant: "revise/brand-film",
    layout: { width: "full", bleed: "media", gutters: { mode: "none" }, spacing: { block: "none" } },
    ...common,
    data: {},
  },
  {
    id: "revise/campaign-teaser",
    type: "campaign-teaser",
    variant: "revise/campaign-teaser",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/before-after",
    type: "before-after",
    variant: "revise/before-after",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/sticky-card-deck",
    type: "editorial-posts",
    variant: "revise/sticky-card-deck",
    layout: { width: "max", bleed: "none", gutters: { mode: "fluid" }, spacing: { block: "lg" } },
    ...common,
    data: {},
  },
  {
    id: "revise/full-bleed-grid",
    type: "social-gallery",
    variant: "revise/full-bleed-grid",
    layout: { width: "full", bleed: "none", gutters: { mode: "none" }, spacing: { block: "md" } },
    ...common,
    data: {},
  },
];

export const reviseShowcaseHome: PagePreset = {
  id: "revise-showcase-home",
  type: "page-preset",
  theme: "revise",
  sections: [
    {
      type: "media-hero",
      preset: "revise/sticky-curtain",
      data: {
        eyebrow: "Volume 01 / Transitional objects",
        heading: "Designed to hold your attention.",
        body: "Directed editorial commerce with quiet motion, deliberate pacing, and tactile discovery.",
        mediaKey: "showcase.hero",
        mediaAlt: "Sculptural monochrome garment study",
        primaryAction: { label: "Shop the edit", href: "#collection" },
        secondaryAction: { label: "Explore the story", href: "#world" },
      },
    },
    {
      type: "media-gallery",
      preset: "revise/wardrobe-rail",
      data: {
        heading: "The wardrobe",
        items: [
          { title: "Outerwear", mediaKey: "showcase.wardrobe.1", href: "#" },
          { title: "Bottoms", mediaKey: "showcase.wardrobe.2", href: "#" },
          { title: "Layers", mediaKey: "showcase.wardrobe.3", href: "#" },
          { title: "Dresses", mediaKey: "showcase.wardrobe.4", href: "#" },
          { title: "Objects", mediaKey: "showcase.wardrobe.5", href: "#" },
        ],
      },
    },
    {
      type: "editorial-grid",
      preset: "revise/dark-promo-grid",
      data: {
        eyebrow: "Selected studies",
        heading: "Material, silhouette, interruption.",
        items: [
          { label: "Form", title: "Structured softness", body: "Tailoring without stiffness.", mediaKey: "showcase.editorial.1", href: "#" },
          { label: "Layer", title: "Quiet volume", body: "Built to move in sections.", mediaKey: "showcase.editorial.2", href: "#" },
          { label: "Object", title: "Useful contrast", body: "One sharp note inside a calm system.", mediaKey: "showcase.editorial.3", href: "#" },
        ],
      },
    },
    {
      type: "statement",
      preset: "revise/editorial-statement",
      data: {
        eyebrow: "The selected",
        heading: "Short beats make the long scenes matter.",
        body: "Revise alternates compact editorial pauses with immersive, held-in-place compositions so the page has cadence rather than endless spectacle.",
      },
    },
    {
      type: "stories",
      preset: "revise/story-rings",
      data: {
        items: [
          { title: "Studio", mediaKey: "showcase.story.1" },
          { title: "Material", mediaKey: "showcase.story.2" },
          { title: "Process", mediaKey: "showcase.story.3" },
          { title: "Night", mediaKey: "showcase.story.4" },
          { title: "Detail", mediaKey: "showcase.story.5" },
        ],
      },
    },
    {
      type: "collection-track",
      preset: "revise/tabbed-products",
      data: {
        eyebrow: "Discovery",
        heading: "The current edit",
        tabs: [
          {
            id: "new",
            label: "New",
            items: [
              { title: "Contour Coat", price: "$310", mediaKey: "showcase.product.1", badge: "New" },
              { title: "Fold Trouser", price: "$180", mediaKey: "showcase.product.2" },
              { title: "Column Knit", price: "$160", mediaKey: "showcase.product.3" },
              { title: "Arc Boot", price: "$220", mediaKey: "showcase.product.4" },
            ],
          },
          {
            id: "best",
            label: "Most viewed",
            items: [
              { title: "Drift Jacket", price: "$280", mediaKey: "showcase.product.5" },
              { title: "Panel Skirt", price: "$150", mediaKey: "showcase.product.6" },
              { title: "Soft Shell", price: "$190", mediaKey: "showcase.product.7" },
            ],
          },
          {
            id: "archive",
            label: "Archive",
            items: [
              { title: "Index Coat", price: "$240", compareAtPrice: "$320", mediaKey: "showcase.product.8", badge: "Archive" },
              { title: "Frame Trouser", price: "$120", compareAtPrice: "$170", mediaKey: "showcase.product.9" },
            ],
          },
        ],
      },
    },
    {
      type: "fullscreen-media-product",
      preset: "revise/scroll-text-reveal",
      data: {
        eyebrow: "Brand world",
        heading: "A slower look.",
        body: "The image holds while the copy reveals in place. Movement serves reading order instead of competing with it.",
        mediaKey: "showcase.world",
        mediaAlt: "Red-lit sculptural fabric",
        product: { title: "Signal Layer", price: "$245", mediaKey: "showcase.product.5" },
      },
    },
    {
      type: "split-media",
      preset: "revise/parallax-diptych",
      data: {
        items: [
          { title: "Soft structure", body: "Dense cotton, clean edge.", mediaKey: "showcase.split.1", href: "#" },
          { title: "Hard shine", body: "Polished leather, deep red.", mediaKey: "showcase.split.2", href: "#" },
        ],
      },
    },
    {
      type: "shop-the-look",
      preset: "revise/hotspot-lookbook",
      data: {
        heading: "Build the look",
        mediaKey: "showcase.look",
        mediaAlt: "Two neutral looks in a dark studio",
        hotspots: [
          { x: 31, y: 44, title: "Contour Coat", price: "$310" },
          { x: 61, y: 66, title: "Arc Boot", price: "$220" },
          { x: 72, y: 36, title: "Signal Layer", price: "$245" },
        ],
      },
    },
    {
      type: "featured-product",
      preset: "revise/pinned-pdp",
      data: {
        eyebrow: "Object 04",
        heading: "Contour Coat",
        body: "A restrained outer layer with a deliberate shoulder and soft internal volume.",
        price: "$310",
        media: [
          { key: "showcase.pdp.1", alt: "Contour Coat front" },
          { key: "showcase.pdp.2", alt: "Contour Coat side" },
          { key: "showcase.pdp.3", alt: "Contour Coat detail" },
        ],
        actions: [{ label: "Add to bag", href: "#bag" }],
      },
    },
    {
      type: "commerce-offers",
      preset: "revise/merch-lab",
      data: {
        eyebrow: "Merchandising lab",
        heading: "Build offers, not just product cards.",
        body: "A reusable commerce presentation for product ideas, attach roles, bundle savings, and optional economics. Hosts can feed it normalized records from any provider.",
        sourceNote: "Neutral package fixture. A host can replace this with any normalized live catalog fixture.",
        currency: "USD",
        showEconomics: true,
        products: [
          {
            id: "core",
            title: "Core product",
            sourceLabel: "Normalized commerce record",
            role: "Hero SKU",
            body: "The main item that gives the offer its reason to exist.",
            proposedRetailCents: 3200,
            fulfillmentCostCents: 1100,
          },
          {
            id: "lifestyle",
            title: "Lifestyle add-on",
            sourceLabel: "Normalized commerce record",
            role: "Cross-sell",
            body: "A visually related item that broadens the use case.",
            proposedRetailCents: 2400,
            fulfillmentCostCents: 700,
          },
          {
            id: "small",
            title: "Small personalized add-on",
            sourceLabel: "Normalized commerce record",
            role: "Checkout upsell",
            body: "Low-friction add-on that can attach near cart or checkout.",
            proposedRetailCents: 1600,
            fulfillmentCostCents: 400,
          },
        ],
        offers: [
          {
            id: "starter",
            badge: "Starter bundle",
            title: "Three-item launch offer",
            body: "Hero SKU + lifestyle add-on + personalized extra.",
            productIds: ["core", "lifestyle", "small"],
            compareAtCents: 7200,
            offerPriceCents: 5800,
            fulfillmentCostCents: 2200,
            ctaLabel: "Add bundle",
          },
        ],
      },
    },
    {
      type: "bundle-builder",
      preset: "revise/sticky-summary",
      data: {
        eyebrow: "Better together",
        heading: "Build a three-object set.",
        body: "The summary stays in reach while the objects continue below it.",
        total: "$650",
        items: [
          { title: "Contour Coat", price: "$310", mediaKey: "showcase.bundle.1" },
          { title: "Column Knit", price: "$160", mediaKey: "showcase.bundle.2" },
          { title: "Fold Trouser", price: "$180", mediaKey: "showcase.bundle.3" },
        ],
      },
    },
    {
      type: "marquee",
      preset: "revise/commerce-marquee",
      data: { items: ["Designed to move", "Built to layer", "Quietly technical", "Made for repeat wear"] },
    },
    {
      type: "collection-split-media",
      preset: "revise/pinned-media-grid",
      data: {
        eyebrow: "Collection 02",
        heading: "Night structure.",
        body: "A held image creates the runway while the collection moves beside it.",
        mediaKey: "showcase.collection",
        mediaAlt: "Dark structural collection study",
        items: [
          { title: "Drift Jacket", price: "$280", mediaKey: "showcase.collection.1" },
          { title: "Panel Skirt", price: "$150", mediaKey: "showcase.collection.2" },
          { title: "Soft Shell", price: "$190", mediaKey: "showcase.collection.3" },
          { title: "Arc Boot", price: "$220", mediaKey: "showcase.collection.4" },
        ],
      },
    },
    {
      type: "brand-film",
      preset: "revise/brand-film",
      data: {
        eyebrow: "Film 01",
        heading: "A study in movement.",
        mediaKey: "showcase.film",
        mediaAlt: "Abstract cinematic fabric still",
      },
    },
    {
      type: "campaign-teaser",
      preset: "revise/campaign-teaser",
      data: {
        eyebrow: "Next volume",
        heading: "Something quieter is coming.",
        body: "A reserved campaign beat after the full-screen film lets the page reset before proof and content.",
        mediaKey: "showcase.campaign",
        mediaAlt: "Abstract campaign teaser",
        action: { label: "Preview the volume", href: "#" },
      },
    },
    {
      type: "logo-track",
      preset: "revise/logo-track",
      data: { items: ["FORM", "INDEX", "FIELD", "OBJECT", "VOLUME", "STUDIO", "DETAIL"] },
    },
    {
      type: "before-after",
      preset: "revise/before-after",
      data: {
        eyebrow: "Contrast study",
        heading: "Move the dividing line.",
        beforeKey: "showcase.before",
        afterKey: "showcase.after",
        beforeAlt: "Soft neutral composition",
        afterAlt: "High-contrast red composition",
      },
    },
    {
      type: "testimonials",
      preset: "revise/testimonials",
      data: {
        eyebrow: "Proof",
        heading: "What stays with people.",
        items: [
          { quote: "The page feels considered without making me fight it.", by: "Editorial review" },
          { quote: "Everything responds quickly, but nothing feels twitchy.", by: "Product tester" },
          { quote: "The product never disappears while I am deciding.", by: "Commerce study" },
        ],
      },
    },
    {
      type: "editorial-posts",
      preset: "revise/sticky-card-deck",
      data: {
        eyebrow: "Journal",
        heading: "Notes from the studio",
        items: [
          { title: "Why the quiet sections matter", meta: "Design note / 05", body: "Rhythm depends on contrast, not constant intensity.", mediaKey: "showcase.post.1" },
          { title: "Making motion feel expensive", meta: "Motion note / 03", body: "Shared timing and restraint create coherence.", mediaKey: "showcase.post.2" },
          { title: "A useful object should stay useful", meta: "Object note / 09", body: "Commerce can be cinematic without hiding the product.", mediaKey: "showcase.post.3" },
        ],
      },
    },
    {
      type: "cta-band",
      preset: "revise/newsletter",
      data: {
        eyebrow: "The edit",
        heading: "One useful dispatch.",
        body: "New objects, working notes, and the occasional first look.",
        action: { label: "Join the list", href: "#" },
      },
    },
    {
      type: "social-gallery",
      preset: "revise/full-bleed-grid",
      data: {
        eyebrow: "Field notes",
        heading: "From the working world",
        items: [
          { title: "Studio 01", mediaKey: "showcase.social.1" },
          { title: "Material 02", mediaKey: "showcase.social.2" },
          { title: "Object 03", mediaKey: "showcase.social.3" },
          { title: "Night 04", mediaKey: "showcase.social.4" },
          { title: "Process 05", mediaKey: "showcase.social.5" },
          { title: "Detail 06", mediaKey: "showcase.social.6" },
        ],
      },
    },
    {
      type: "faq",
      preset: "revise/faq",
      data: {
        eyebrow: "Details",
        heading: "Before you ask.",
        items: [
          { q: "What makes Revise portable?", a: "The host owns data and providers; the theme owns presentation and interaction character." },
          { q: "Does the theme require a framework?", a: "No. The canonical runtime is semantic HTML, CSS, JSON contracts, and small TypeScript controllers." },
          { q: "What happens with reduced motion?", a: "Travel, parallax, ambient loops, and large reveals simplify while information and focus behavior remain intact." },
        ],
      },
    },
    {
      type: "trust-row",
      preset: "revise/trust-row",
      data: {
        items: [
          { title: "Measured", body: "Motion is tokenized." },
          { title: "Touch-first", body: "44px control floor." },
          { title: "Portable", body: "No provider authority." },
          { title: "Accessible", body: "Focus returns home." },
        ],
      },
    },
  ],
};
