-- Register iam-cms-pipeline Agent Sam tools (Python Worker service binding).
INSERT OR REPLACE INTO agentsam_tools (
  id,
  tool_key,
  tool_name,
  display_name,
  tool_category,
  handler_type,
  handler_key,
  description,
  input_schema,
  handler_config,
  risk_level,
  requires_approval,
  requires_confirmation,
  is_active,
  is_degraded,
  workspace_scope,
  sort_priority,
  is_global,
  updated_at
) VALUES
(
  'ast_cms_pipeline_prototype',
  'cms_pipeline_prototype',
  'cms_pipeline_prototype',
  'CMS Pipeline Prototype',
  'cms',
  'agent',
  'cms_pipeline_prototype',
  'Workers AI section/HTML prototype via iam-cms-pipeline (read-only proposal; apply with agentsam_cms_write).',
  '{"type":"object","properties":{"goal":{"type":"string","description":"What to build or change"},"page_id":{"type":"string"},"project_slug":{"type":"string"}},"required":["goal"]}',
  '{"handler":"cms_pipeline_prototype","module":"tools/builtin/cms.js"}',
  'medium',
  0,
  0,
  1,
  0,
  '["*"]',
  14,
  1,
  unixepoch()
),
(
  'ast_cms_pipeline_extract',
  'cms_pipeline_extract',
  'cms_pipeline_extract',
  'CMS Pipeline Extract',
  'cms',
  'agent',
  'cms_pipeline_extract',
  'Parse HTML for data-cms-section slots and default D1 section stubs (Python BeautifulSoup).',
  '{"type":"object","properties":{"html":{"type":"string"},"content":{"type":"string"}},"required":["html"]}',
  '{"handler":"cms_pipeline_extract","module":"tools/builtin/cms.js"}',
  'low',
  0,
  0,
  1,
  0,
  '["*"]',
  15,
  1,
  unixepoch()
),
(
  'ast_cms_pipeline_inject',
  'cms_pipeline_inject',
  'cms_pipeline_inject',
  'CMS Pipeline Inject',
  'cms',
  'agent',
  'cms_pipeline_inject',
  'Splice section HTML into a page shell (preview only — persist via save-injected / cms_write).',
  '{"type":"object","properties":{"shell_html":{"type":"string"},"section_name":{"type":"string"},"fragment_html":{"type":"string"},"position":{"type":"string","enum":["replace","start","end"]}},"required":["shell_html","section_name","fragment_html"]}',
  '{"handler":"cms_pipeline_inject","module":"tools/builtin/cms.js"}',
  'medium',
  1,
  0,
  1,
  0,
  '["*"]',
  16,
  1,
  unixepoch()
),
(
  'ast_cms_pipeline_bootstrap',
  'cms_pipeline_bootstrap',
  'cms_pipeline_bootstrap',
  'CMS Pipeline Bootstrap',
  'cms',
  'agent',
  'cms_pipeline_bootstrap',
  'Load CMS pages + sections tree from D1 via Python pipeline worker.',
  '{"type":"object","properties":{"project_slug":{"type":"string"},"project":{"type":"string"}},"required":["project_slug"]}',
  '{"handler":"cms_pipeline_bootstrap","module":"tools/builtin/cms.js"}',
  'low',
  0,
  0,
  1,
  0,
  '["*"]',
  17,
  1,
  unixepoch()
);
