"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element -- Portable React surface uses host navigation and original media delivery. */
import { useEffect, useRef, useState } from "react";
import type { SiteDocument, SiteSection, SiteContentBlock } from "../../../packages/site-contracts/src/site-document";
import { editableSectionFields, applySectionFieldEdit } from "../../../packages/site-contracts/src/section-fields";
import { catalog, createSection, moveItem } from "../../../packages/studio-sections/src/catalog";
import { parseDocument, safeUrl, validateBoundary } from "../../../packages/studio-sections/src/validation";
import { previewFixture } from "../../../packages/studio-sections/src/preview-fixture";
import { MountedSection, SitePreview } from "../../../packages/studio-sections/src/MountedSection";
import { fixtures } from "./fixtures";
import { loadRevisions, saveRevision, type DraftRevision } from "./drafts";
import "./studio.css";

type Tab = "page"|"global"|"library"|"media"|"revisions";
type MediaEntry = {url:string;alt:string};
const uid = () => crypto.randomUUID();
function download(name:string, content:string) {
  const url=URL.createObjectURL(new Blob([content],{type:"application/json"}));
  const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);
}
function Field({label,value,onChange,large,type="text"}:{label:string;value:string;onChange:(v:string)=>void;large?:boolean;type?:string}) {
  return <label className="studio-field"><span>{label}</span>{large?<textarea value={value} onChange={e=>onChange(e.target.value)} />:<input type={type} value={value} onChange={e=>onChange(e.target.value)} />}</label>;
}
function Order({index,length,move,remove,duplicate}:{index:number;length:number;move:(delta:number)=>void;remove:()=>void;duplicate?:()=>void}) {
  return <div className="studio-order"><button disabled={index===0} aria-label="Move up" onClick={()=>move(-1)}>Up</button><button disabled={index===length-1} aria-label="Move down" onClick={()=>move(1)}>Down</button>{duplicate&&<button onClick={duplicate}>Duplicate</button>}<button onClick={remove}>Remove</button></div>;
}
function DataFields({data,blockId,onEdit,mediaKeys}:{data:Record<string,unknown>;blockId?:string;onEdit:(key:string,input:string|boolean,blockId?:string)=>void;mediaKeys:string[]}) {return <>{editableSectionFields(data).map(field=>field.kind==="media"?<label key={field.key} className="studio-field">{field.label}<select value={String(field.value)} onChange={e=>onEdit(field.key,e.target.value,blockId)}><option value="">No media</option>{field.value&&!mediaKeys.includes(String(field.value))&&<option value={String(field.value)}>Unavailable · {String(field.value)}</option>}{mediaKeys.map(key=><option key={key} value={key}>{key}</option>)}</select><small>Register customer assets in Media.</small></label>:field.kind==="boolean"?<label className="studio-check" key={field.key}><input type="checkbox" checked={Boolean(field.value)} onChange={e=>onEdit(field.key,e.target.checked,blockId)} />{field.label}</label>:<Field key={field.key} label={field.label} value={String(field.value)} type={field.kind==="number"?"number":"text"} large={field.kind==="long-text"} onChange={v=>onEdit(field.key,v,blockId)} />)}</>;}
export default function Studio({initialTab="page"}:{initialTab?:Tab}) {
  const [doc,setDoc]=useState<SiteDocument>(fixtures[0]);
  const [pageId,setPageId]=useState(fixtures[0].pages[0].id);
  const [selection,setSelection]=useState(fixtures[0].pages[0].sections[0]?.id || "");
  const [tab,setTab]=useState<Tab>(initialTab);
  const [width,setWidth]=useState("fluid");
  const [notice,setNotice]=useState("Sample draft · no customer site connected");
  const [revisions,setRevisions]=useState<DraftRevision[]>([]);
  const [preview,setPreview]=useState<SiteDocument|null>(null);
  const [media,setMedia]=useState<Record<string,Record<string,MediaEntry>>>({});
  const [mediaKey,setMediaKey]=useState("");
  const [mediaUrl,setMediaUrl]=useState("");
  const [mediaAlt,setMediaAlt]=useState("");
  const [dirty,setDirty]=useState(false);
  const [panel,setPanel]=useState<"outline"|"canvas"|"inspector">("canvas");
  const importer=useRef<HTMLInputElement>(null);
  const shell=useRef<HTMLElement>(null);
  const [expanded,setExpanded]=useState(false);
  useEffect(()=>{
    const viewport=window.visualViewport;
    const resize=()=>{const root=shell.current;if(!root)return;root.style.setProperty("--studio-viewport-height",(viewport?.height||window.innerHeight)+"px");root.dataset.keyboard=String((viewport?.height||window.innerHeight)<window.innerHeight*.78);};
    resize();viewport?.addEventListener("resize",resize);window.addEventListener("resize",resize);
    return()=>{viewport?.removeEventListener("resize",resize);window.removeEventListener("resize",resize);};
  },[]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{const canvas=shell.current?.querySelector<HTMLElement>(".studio-canvas");const selected=Array.from(canvas?.querySelectorAll<HTMLElement>("[data-section-id]")||[]).find(el=>el.dataset.sectionId===selection);if(canvas&&selected)canvas.scrollTop+=selected.getBoundingClientRect().top-canvas.getBoundingClientRect().top;});return()=>cancelAnimationFrame(frame);},[selection,pageId,panel]);
  const page=doc.pages.find(p=>p.id===pageId)||doc.pages[0];
  const section=page.sections.find(s=>s.id===selection);
  const assets=media[doc.id]||{};
  const resolveMedia=(key:string)=>assets[key]?.url||null;
  useEffect(()=>{const refresh=()=>{try{setRevisions(loadRevisions());}catch(e){setNotice(String(e));}};const frame=requestAnimationFrame(refresh);window.addEventListener("storage",refresh);return()=>{cancelAnimationFrame(frame);window.removeEventListener("storage",refresh);};},[]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  function edit(action:(draft:SiteDocument)=>void) { const next=structuredClone(doc);action(next);setDoc(next);setDirty(true);setPreview(null); }
  function editSection(action:(s:SiteSection)=>void) {edit(d=>{const s=d.pages.find(p=>p.id===page.id)?.sections.find(s=>s.id===section?.id);if(s)action(s);});}
  function chooseDocument(next:SiteDocument){setDoc(structuredClone(next));setPageId(next.pages[0].id);setSelection(next.pages[0].sections[0]?.id||"");setPreview(null);setDirty(false);setNotice("Sample draft loaded · save a revision to keep edits");}
  function save() {try{const r=saveRevision(doc);setRevisions(loadRevisions());setDirty(false);setNotice("Draft revision saved on this browser · "+new Date(r.createdAt).toLocaleTimeString());}catch(e){setNotice("Draft was not saved: "+String(e));}}
  function openPreview() {try{const revision=saveRevision(doc);setRevisions(loadRevisions());setDirty(false);setPreview(revision.document);setPanel("canvas");setNotice("Previewing immutable local revision "+revision.id.slice(0,8));}catch(e){setNotice(String(e));}}
  function addSection(preset:string){const s=createSection(preset,uid());edit(d=>d.pages.find(p=>p.id===page.id)!.sections.push(s));setSelection(s.id);setTab("page");setPanel("inspector");}
  function editData(key:string,input:string|boolean,blockId?:string){
    const next=structuredClone(doc),s=next.pages.find(p=>p.id===page.id)!.sections.find(s=>s.id===section?.id);
    if(!s)return;
    const data=blockId?s.blocks?.find(b=>b.id===blockId)?.data:s.data;if(!data)return;
    const result=applySectionFieldEdit(data,key,input,{mediaKeys:new Set(Object.keys(assets))});
    if(!result.ok){setNotice("Edit rejected: "+result.reason);return;}
    setDoc(next);setDirty(true);setPreview(null);
  }

  const pageControls=<>
    <h2>Pages</h2>{doc.pages.map((p,i)=><div className="studio-listitem" key={p.id}><button className={page.id===p.id?"active":""} onClick={()=>{setPageId(p.id);setSelection(p.sections[0]?.id||"");}}><strong>{p.title}</strong><small>{p.path}</small></button><Order index={i} length={doc.pages.length} move={delta=>edit(d=>{d.pages=moveItem(d.pages,i,delta);})} remove={()=>{if(doc.pages.length===1){setNotice("Keep at least one page");return;}edit(d=>{d.pages.splice(i,1);});}} /></div>)}
    <button className="studio-full" onClick={()=>{const id=uid();edit(d=>{d.pages.push({id,path:"/page-"+id.slice(0,8)+"/",title:"Untitled page",description:"",sections:[]});});setPageId(id);setSelection("");}}>Add page</button>
    <h2>Sections</h2>{page.sections.map((s,i)=><div className="studio-listitem" key={s.id}><button className={s.id===selection?"active":""} onClick={()=>{setSelection(s.id);setPanel("inspector");}}><strong>{catalog.find(c=>c.preset===s.preset)?.title||s.preset}</strong><small>{s.id.slice(0,18)}</small></button><Order index={i} length={page.sections.length} move={delta=>edit(d=>{const p=d.pages.find(p=>p.id===page.id)!;p.sections=moveItem(p.sections,i,delta);})} duplicate={()=>edit(d=>{const p=d.pages.find(p=>p.id===page.id)!;const copy=structuredClone(s);copy.id=uid();copy.blocks=copy.blocks?.map(b=>({...b,id:uid()}));p.sections.splice(i+1,0,copy);})} remove={()=>{edit(d=>{d.pages.find(p=>p.id===page.id)!.sections.splice(i,1);});setSelection("");}} /></div>)}
    <button className="studio-full" onClick={()=>{setTab("library");setPanel("canvas");}}>Add section</button>
    <h2>Page compositions</h2>{fixtures.slice(0,2).map(f=><button className="studio-full" key={f.id} onClick={()=>{const p=structuredClone(f.pages[0]);p.id=uid();p.title=f.brand.name+" sample layout";p.path="/layout-"+p.id.slice(0,8)+"/";p.sections=p.sections.map(s=>({...s,id:uid(),blocks:s.blocks?.map(b=>({...b,id:uid()}))}));edit(d=>d.pages.push(p));setPageId(p.id);setSelection(p.sections[0]?.id||"");}}>{f.brand.name} layout</button>)}
  </>;
  const globals=<>
    <h2>Site identity</h2><Field label="Brand name" value={doc.brand.name} onChange={v=>edit(d=>{d.brand.name=v;})} /><Field label="Home URL" value={doc.brand.home} onChange={v=>edit(d=>{d.brand.home=v;})} /><Field label="Description" value={doc.brand.description} large onChange={v=>edit(d=>{d.brand.description=v;})} /><Field label="Theme" value={doc.theme} onChange={v=>edit(d=>{d.theme=v;})} />
    <h2>Design tokens</h2>{(["accent","accentSoft","canvas","paper","ink"] as const).map(key=><Field key={key} label={key} type="color" value={doc.design?.[key]||"#FFFFFF"} onChange={v=>edit(d=>{d.design={...d.design,[key]:v};})} />)}
    <h2>Global header</h2>{(["sticky","pill"] as const).map(key=><label className="studio-check" key={key}><input type="checkbox" checked={doc.header.settings[key]} onChange={e=>edit(d=>{d.header.settings[key]=e.target.checked;})} />{key}</label>)}
    <label className="studio-check"><input type="checkbox" checked={doc.header.announcement.enabled} onChange={e=>edit(d=>{d.header.announcement.enabled=e.target.checked;})} />Announcement</label><Field label="Announcement messages (one per line)" value={doc.header.announcement.messages.join("\n")} large onChange={v=>edit(d=>{d.header.announcement.messages=v.split("\n").filter(Boolean);})} />
    {doc.header.blocks.map((b,i)=><fieldset key={b.id}><legend>{b.type}</legend><Field label="Label" value={b.label} onChange={v=>edit(d=>{d.header.blocks[i].label=v;})} />{b.type!=="action"&&<Field label="URL" value={b.href||""} onChange={v=>edit(d=>{d.header.blocks[i].href=v;})} />}{b.type==="action"&&<label className="studio-field">Action<select value={b.action} onChange={e=>edit(d=>{d.header.blocks[i].action=e.target.value as typeof b.action;})}>{["menu","search","discover","bag"].map(a=><option key={a}>{a}</option>)}</select><small>Host capability required</small></label>}<Order index={i} length={doc.header.blocks.length} move={delta=>edit(d=>{d.header.blocks=moveItem(d.header.blocks,i,delta);})} remove={()=>edit(d=>{d.header.blocks.splice(i,1);})} /></fieldset>)}
    <div className="studio-row">{(["brand","link","action"] as const).map(type=><button key={type} onClick={()=>edit(d=>{d.header.blocks.push({id:uid(),type,label:type==="brand"?d.brand.name:"New "+type,...(type==="action"?{action:"menu" as const}:{href:"/"})});})}>Add {type}</button>)}</div>
    <h2>Global footer</h2><Field label="Copyright" value={doc.footer.settings.copyright} onChange={v=>edit(d=>{d.footer.settings.copyright=v;})} /><label className="studio-field">Surface<select value={doc.footer.settings.background} onChange={e=>edit(d=>{d.footer.settings.background=e.target.value as typeof d.footer.settings.background;})}>{["canvas","paper","muted","inverse"].map(v=><option key={v}>{v}</option>)}</select></label>
    {doc.footer.blocks.map((b,i)=><fieldset key={b.id}><legend>{b.type}</legend><Field label="Title" value={b.title} onChange={v=>edit(d=>{d.footer.blocks[i].title=v;})} /><Field label="Description" value={b.description||""} onChange={v=>edit(d=>{d.footer.blocks[i].description=v;})} />{b.links?.map((l,j)=><div key={l.id}><Field label="Link label" value={l.label} onChange={v=>edit(d=>{d.footer.blocks[i].links![j].label=v;})} /><Field label="Link URL" value={l.href} onChange={v=>edit(d=>{d.footer.blocks[i].links![j].href=v;})} /><Order index={j} length={b.links!.length} move={delta=>edit(d=>{d.footer.blocks[i].links=moveItem(d.footer.blocks[i].links!,j,delta);})} remove={()=>edit(d=>{d.footer.blocks[i].links!.splice(j,1);})} /></div>)}<button onClick={()=>edit(d=>{(d.footer.blocks[i].links ||= []).push({id:uid(),label:"New link",href:"/"});})}>Add link</button><Order index={i} length={doc.footer.blocks.length} move={delta=>edit(d=>{d.footer.blocks=moveItem(d.footer.blocks,i,delta);})} remove={()=>edit(d=>{d.footer.blocks.splice(i,1);})} /></fieldset>)}
    <div className="studio-row">{(["menu","newsletter","social","legal"] as const).map(type=><button key={type} onClick={()=>edit(d=>{d.footer.blocks.push({id:uid(),type,title:"New "+type,links:[]});})}>Add {type}</button>)}</div>
  </>;
  return <main ref={shell} className="studio" data-panel={panel} data-tab={tab} data-expanded={expanded}>
    <header className="studio-top"><a className="studio-logo" href="/">IA<span>CMS STUDIO</span></a><label className="studio-site"><span className="sr-only">Sample site</span><select value={fixtures.some(f=>f.id===doc.id)?doc.id:"imported"} onChange={e=>{const next=fixtures.find(f=>f.id===e.target.value);if(next){if(dirty&&!window.confirm("Switch sample and discard unsaved edits?"))return;chooseDocument(next);}}}>{!fixtures.some(f=>f.id===doc.id)&&<option value="imported">{doc.brand.name}</option>}{fixtures.map(f=><option key={f.id} value={f.id}>{f.brand.name}</option>)}</select><small>Sample workspace</small></label><div className="studio-topactions"><button onClick={()=>importer.current?.click()}>Import</button><button onClick={()=>{const issues=validateBoundary(doc);if(issues.length){setNotice(issues.join("; "));return;}download(doc.id+".site-document.json",JSON.stringify(doc,null,2));}}>Export</button><button onClick={openPreview}>Preview revision</button><button className="primary" onClick={save}>Save draft</button><button disabled title="Authorized host persistence and publication adapter required">Publish</button></div></header>
    <input hidden ref={importer} type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(dirty&&!window.confirm("Import and replace unsaved draft?"))return;const next=parseDocument(await file.text());chooseDocument(next);setDirty(true);setNotice("Canonical document imported; unknown presets are preserved");}catch(error){setNotice("Import rejected: "+String(error));}finally{e.target.value="";}}} />
    <nav className="studio-nav" aria-label="Studio tools">{([["page","Pages"],["global","Global site"],["library","Library"],["media","Media"],["revisions","Revisions"]] as const).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);setPanel(id==="page"?"outline":id==="global"?"inspector":"canvas");}}>{label}</button>)}</nav>
    <aside className="studio-outline"><div className="studio-sheetbar"><strong>Pages & sections</strong><button onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded}>{expanded?"Compact":"Expand"}</button><button onClick={()=>{setPanel("canvas");setExpanded(false);}}>Close</button></div>{tab==="page"?pageControls:<><h2>{doc.brand.name}</h2><p>{tab==="library"?"Compiled section source. Choose a section to mount in the current page.":tab==="media"?"Map logical keys to this site's own assets.":tab==="revisions"?"Saved browser snapshots. Customer publishing is not connected.":"Brand, header and footer belong to the whole site."}</p><p className="studio-badge">Canonical SiteDocument v1</p><button onClick={()=>{setTab("page");setPanel("outline");}}>Back to pages</button><a href="/library">Open Design Atlas</a><a href="https://github.com/SamPrimeaux/inneranimalmedia-cms">Canonical repository</a></>}</aside>
    <section className="studio-workspace">
      <div className="studio-canvasbar"><div><strong>{tab==="library"?"Section library":tab==="media"?"Site media":tab==="revisions"?"Draft history":page.title}</strong><small>{preview?"Saved revision preview":dirty?"Unsaved draft":"Local authoring"} · {page.path}</small></div><label className="studio-size"><span className="sr-only">Viewport</span><select value={width} onChange={e=>setWidth(e.target.value)}><option value="fluid">Fit</option><option value="390">Phone · 390</option><option value="834">Tablet · 834</option><option value="1440">Wide · 1440</option></select></label>{preview&&<button onClick={()=>setPreview(null)}>Return to draft</button>}</div>
      {tab==="library"?<div className="studio-catalog">{catalog.map(entry=>{const s=previewFixture(entry.preset,doc);const seed=doc.pages.flatMap(p=>p.sections).find(s=>s.preset===entry.preset);return <article key={entry.preset}><div className="studio-cardpreview"><MountedSection section={seed||s} site={doc} resolveMedia={resolveMedia} /></div><div className="studio-cardmeta"><span className="studio-badge">SiteDocument-bound</span><h2>{entry.title}</h2><p>{entry.description}</p><code>{entry.preset}</code><small>Source: packages/studio-sections/src/MountedSection.tsx</small><small>{entry.capabilities.length?"Requires: "+entry.capabilities.join(", "):"No external capability"}</small><button className="primary" onClick={()=>addSection(entry.preset)}>Add to {page.title}</button></div></article>;})}</div>:
      tab==="media"?<div className="studio-content"><h1>Media for {doc.brand.name}</h1><p>Assets are scoped to this sample site. HTTPS mappings and device previews stay in this session; original files are never modified.</p><Field label="Logical media key" value={mediaKey} onChange={setMediaKey} /><Field label="Customer HTTPS delivery URL" value={mediaUrl} onChange={setMediaUrl} /><Field label="Alt description" value={mediaAlt} onChange={setMediaAlt} /><button onClick={()=>{if(!/^[a-z0-9][a-z0-9._/-]*$/i.test(mediaKey)||!mediaUrl.startsWith("https:")||!safeUrl(mediaUrl)){setNotice("Enter a stable key and safe HTTPS image URL");return;}setMedia(m=>({...m,[doc.id]:{...m[doc.id],[mediaKey]:{url:mediaUrl,alt:mediaAlt}}}));setNotice("Session media mapping registered. Ownership must be validated by the publishing host.");}}>Register session mapping</button><label className="studio-field">Preview a device image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(!mediaKey||!["image/png","image/jpeg","image/webp","image/gif"].includes(file.type)||file.size>20_000_000){setNotice("Choose a logical key and PNG, JPEG, WebP or GIF up to 20 MB");return;}setMedia(m=>({...m,[doc.id]:{...m[doc.id],[mediaKey]:{url:URL.createObjectURL(file),alt:mediaAlt}}}));setNotice("Device image available for this session only");}} /></label>{Object.entries(assets).map(([key,asset])=><article className="studio-asset" key={key}><img src={asset.url} alt={asset.alt} /><div><strong>{key}</strong><p>{asset.alt}</p><button onClick={()=>setMedia(m=>{const next={...m,[doc.id]:{...m[doc.id]}};delete next[doc.id][key];return next;})}>Remove mapping</button></div></article>)}</div>:
      tab==="revisions"?<div className="studio-content"><h1>Local revisions</h1><p>Snapshots are immutable copies stored in this browser. Export documents for transfer. No remote synchronization or customer publication is claimed.</p>{!revisions.length&&<p>No revisions saved yet.</p>}{[...revisions].reverse().map(r=><article className="studio-revision" key={r.id}><div><strong>{r.document.brand.name}</strong><small>{new Date(r.createdAt).toLocaleString()} · {r.id.slice(0,8)}</small></div><button onClick={()=>{chooseDocument(r.document);setPreview(structuredClone(r.document));setTab("page");setPanel("canvas");setNotice("Previewing local revision "+r.id.slice(0,8));}}>Preview</button><button onClick={()=>{chooseDocument(r.document);setDirty(true);setTab("page");}}>Restore as draft</button><button onClick={()=>download(r.document.id+"-"+r.id.slice(0,8)+".json",JSON.stringify(r.document,null,2))}>Export</button></article>)}</div>:
      <div className="studio-canvas"><div className="studio-viewport" style={{width:width==="fluid"?"100%":Number(width)}}><SitePreview document={preview||doc} pageId={page.id} resolveMedia={resolveMedia} selected={preview?undefined:selection} select={preview?undefined:id=>{setSelection(id);setPanel("inspector");}} /></div></div>}
    </section>
    <aside className="studio-inspector"><div className="studio-sheetbar"><strong>{tab==="global"?"Global site":section?"Edit section":"Page settings"}</strong><button onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded}>{expanded?"Compact":"Expand"}</button><button onClick={()=>{setPanel("canvas");setExpanded(false);}}>Close</button></div>{tab==="global"?globals:tab==="page"?<><details className="studio-page-settings"><summary>Page settings</summary><Field label="Title" value={page.title} onChange={v=>edit(d=>{d.pages.find(p=>p.id===page.id)!.title=v;})} /><Field label="Route" value={page.path} onChange={v=>edit(d=>{d.pages.find(p=>p.id===page.id)!.path=v;})} /><Field label="Description" value={page.description} large onChange={v=>edit(d=>{d.pages.find(p=>p.id===page.id)!.description=v;})} /></details>{section?<><h2>{catalog.find(c=>c.preset===section.preset)?.title||section.preset}</h2><code>{section.preset}</code><details className="studio-section-settings"><summary>Section settings</summary>{(["surface","spacing","minHeight"] as const).map(key=><label key={key} className="studio-field">{key}<select value={section.settings[key]||""} onChange={e=>editSection(s=>{Object.assign(s.settings,{[key]:e.target.value});})}>{(key==="surface"?["canvas","paper","muted","inverse","image"]:key==="spacing"?["none","sm","md","lg"]:["auto","screen"]).map(v=><option key={v}>{v}</option>)}</select></label>)}<Field label="Background media key" value={section.settings.backgroundMediaKey||""} onChange={v=>editSection(s=>{s.settings.backgroundMediaKey=v;})} /></details><h3>Content</h3><DataFields data={section.data} onEdit={editData} mediaKeys={Object.keys(assets)} /><h3>Ordered blocks</h3>{section.blocks?.map((b,i)=><fieldset key={b.id}><legend>{b.type} {i+1}</legend><DataFields data={b.data} blockId={b.id} onEdit={editData} mediaKeys={Object.keys(assets)} /><Order index={i} length={section.blocks!.length} move={delta=>editSection(s=>{s.blocks=moveItem(s.blocks!,i,delta);})} duplicate={()=>editSection(s=>{s.blocks!.splice(i+1,0,{...structuredClone(b),id:uid()});})} remove={()=>editSection(s=>{s.blocks!.splice(i,1);})} /></fieldset>)}<button onClick={()=>editSection(s=>{(s.blocks ||= []).push({id:uid(),type:"item",data:{title:"",caption:"",body:"",mediaKey:"",alt:"",href:"",ctaLabel:""}} as SiteContentBlock);})}>Add content block</button></>:<p>Select a section to edit its content, media and ordered blocks.</p>}</>:<><h2>Readiness</h2><p>Direct React mounting · canonical JSON</p><p>Local drafts and revision previews available.</p><p>Host authentication, asset ownership, database synchronization and customer publishing require integration.</p><button disabled>Customer publish unavailable</button></>}</aside>
    <footer className="studio-status" role="status">{notice}<span>{dirty?"Unsaved changes":"Draft workspace"}</span></footer>
    <nav className="studio-mobile" aria-label="Mobile editor panels">{(["outline","canvas","inspector"] as const).map(id=><button className={panel===id?"active":""} key={id} onClick={()=>{setPanel(id);setExpanded(false);}}>{id==="outline"?"Pages":id==="canvas"?"Preview":"Edit"}</button>)}</nav>
  </main>;
}
